{
 "title": "Ingress Controller Dashboard",
 "description": "Ingress Controller (Prometheus) dashboard developed by FuchiCorp.",
 "tags": [
  "ingress-controller",
  "common-tools"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "deployment_namespace", "label": "Namespace", "query": "tools" },
   {
    "name": "deployment_name",
    "label": "Deployment",
    "query": "ingress-controller-tools-ingress-nginx-controller"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"tools\",pod=~\"ingress-controller-tools-ingress-nginx-controller.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_metadata_generation{deployment=\"ingress-controller-tools-ingress-nginx-controller\",namespace=\"tools\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"ingress-controller-tools-ingress-nginx-controller\",namespace=\"tools\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"tools\",pod=~\"ingress-controller-tools-ingress-nginx-controller.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"tools\",pod=~\"ingress-controller-tools-ingress-nginx-controller.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Cluster Pod Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable_pods{node=~\".*\"})",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"tools\",pod=~\"ingress-controller-tools-ingress-nginx-controller.*\"}) / 1024^3"
    }
   ]
  }
 ]
}